{% set version = "2.6.0" %}

package:
  name: pdal
  version: {{ version }}_asp3.5.0

source:
  git_url: https://github.com/PDAL/PDAL.git
  #git_url: git@github.com:PDAL/PDAL.git
  git_tag: {{ version }}

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('pdal', max_pin='x.x') }}

requirements:
  build:
    - cmake 3.27.9
    - make
    - pkg-config
    - c-compiler                1.9.0
    - compilers                 1.9.0
    - cxx-compiler              1.9.0
    - fortran-compiler          1.9.0

  host:
    - libgdal 3.7.1
    - geotiff 1.7.1
    - libpq 15.4
    - c-ares 1.34.5
    - libsqlite 3.49.1
    - mpfr 4.2.1
    - llvm-openmp 16.0.6
    - nanoflann 1.6.1
    - networkx 3.4.2
    - nss 3.110
    - rclone 1.69.1
    - scipy 1.15.2
    - python 3.11.6
    - sqlite 3.49.1
    - zstd 1.5.7
    # - libkml
    - eigen 3.4.0
    # - nitro
    - curl 8.4.0
    - zlib 1.3.1
    - hdf5 1.14.1
    - tiledb 2.16.3
    - zstd 1.5.7
    - libxml2 2.11.5
    # - draco
    - openssl 3.1.8
    # - ceres-solver
    - mkl  # [win]
    - blas  2.131

  run:
    - libgdal 3.7.1
    - geotiff 1.7.1
    - libpq 15.4
    - c-ares 1.34.5
    - libsqlite 3.49.1
    - mpfr 4.2.1
    - llvm-openmp 16.0.6
    - nanoflann 1.6.1
    - networkx 3.4.2
    - nss 3.110
    - rclone 1.69.1
    - scipy 1.15.2
    - python 3.11.6
    - sqlite 3.49.1
    - zstd 1.5.7
    # - libkml
    - eigen 3.4.0
    # - nitro
    - curl 8.4.0
    - zlib 1.3.1
    - hdf5 1.14.1
    - tiledb 2.16.3
    - zstd 1.5.7
    - libxml2 2.11.5
    # - draco
    - openssl 3.1.8
    # - ceres-solver
    - mkl  # [win]
    - blas  2.131

  run_constrained:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
